baseURL = "https://kaedenbryer.com/blog/"
languageCode = 'en-us'
title = '''Kaeden's Blog'''
theme = 'PaperMod'

[menu]
  [[menu.main]]
    name="Home"
    url= "https://kaedenbryer.com"
    weight = 10

[params]
  ShowBreadCrumbs = false